server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER-API
          predicates:
          - Path=/api/v1/customers/**

  mvc:
    log-resolved-exception: true
