server:
  port: 8082

spring:
  application:
    name: notification

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create