server:
  port: 8080

spring:
  application:
    name: customer-api

  # db
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create

  mvc:
    log-resolved-exception: true

app:
  fraud-api:
    # we indicate the name of the service instead of the domain url
    url: http://fraud-api/api/v1/fraud-check/{customerId}
