server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetch-registry: false
    # This app is eureka server so we dont want to register it as service
    register-with-eureka: false