version: "3.8"

services:
  customer-db:
    image: postgres:15-alpine
    container_name: customer-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customerdb
    ports:
      - "5432:5432"
    volumes:
      - customer-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - customer-db

volumes:
  customer-data:
    name: customer-data
  pgadmin:
    name: pgadmin
